In [4]:
# 1 Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.


import numpy as np

arr = np.arange(6)
print(arr.dtype)


int64


In [5]:
# 2 Given a NumPy array 'arr', check if its data type is float64.

arr = np.array([1.5, 2.6, 3.7])
is_float64 = arr.dtype == np.float64
print(is_float64)


True


In [6]:
# 3 Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

arr = np.array([1+2j, 3+4j, 5+6j])
print(arr)


[1.+2.j 3.+4.j 5.+6.j]


In [7]:
# 4 Convert an existing NumPy array 'arr' of integers to float32 data type.

arr = np.array([1, 2, 3, 4, 5])
arr_float32 = arr.astype(np.float32)
print(arr_float32)


[1. 2. 3. 4. 5.]


In [8]:
# 5 Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

arr = np.array([1.53434, 2.62542, 3.25227], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print(arr_float32)


[1.53434 2.62542 3.25227]


In [9]:
# 6 Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr = np.array([1.5, 2.6, 3.7])
print(array_attributes(arr))


((3,), 3, dtype('float64'))


In [10]:
# 7 Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

def array_dimension(arr):
    return arr.ndim

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_dimension(arr))


2


In [11]:
# 8 Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

def item_size_info(arr):
    return arr.itemsize, arr.nbytes

arr = np.array([1, 2, 3, 4, 5])
print(item_size_info(arr))


(8, 40)


In [12]:
# 9 Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

def array_strides(arr):
    return arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_strides(arr))



(24, 8)


In [13]:
# 10 Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array

def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(shape_stride_relationship(arr))


((2, 3), (24, 8))


In [14]:
#  11 Create a function create_zeros_array that takes an integer n as input and returns a NumPy array of zeros with n elements.
def create_zeros_array(n):
    return np.zeros(n)

print(create_zeros_array(5))


[0. 0. 0. 0. 0.]


In [15]:
# 12 Write a function create_ones_matrix that takes integers rows and cols as inputs and generates a 2D NumPy array filled with ones of size rows x cols.

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

print(create_ones_matrix(3, 4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
# 13 Write a function generate_range_array that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from start, ending at stop (exclusive), and with the specified step.

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

print(generate_range_array(1, 10, 2))



[1 3 5 7 9]


In [17]:
# 14 Design a function generate_linear_space that takes two floats start, stop, and an integer num as arguments and generates a NumPy array with num equally spaced values between start and stop (inclusive).

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

print(generate_linear_space(1.0, 5.0, 10))


[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [18]:
#  15 Create a function create_identity_matrix that takes an integer n as input and generates a square identity matrix of size n x n using numpy.eye.

def create_identity_matrix(n):
    return np.eye(n)

print(create_identity_matrix(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# 16 Write a function that takes a Python list and converts it into a NumPy array

def list_to_array(lst):
    return np.array(lst)

print(list_to_array([1, 2, 3, 4, 5]))


[1 2 3 4 5]


In [20]:
# 17  Create a NumPy array and demonstrate the use of numpy.view to create a new array object with the same data.

arr = np.array([1, 2, 3, 4, 5])
view_arr = arr.view()
print(view_arr)


[1 2 3 4 5]


In [21]:
# 18 Write a function that takes two NumPy arrays and concatenates them along a specified axis.

def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(concatenate_arrays(arr1, arr2))


[1 2 3 4 5 6]


In [22]:
# 19  Create two NumPy arrays with different shapes and concatenate them horizontally using numpy.concatenate.

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6], [7, 8, 9]])
arr1_padded = np.pad(arr1, ((0, 1), (0, 0)), 'constant')
result = np.concatenate((arr1_padded, arr2), axis=1)
print(result)


[[1 2 3 4 5 6]
 [0 0 0 7 8 9]]


In [23]:
#20  Write a function that vertically stacks multiple NumPy arrays given as a list.
def stack_arrays_vertically(arr_list):
    return np.vstack(arr_list)

arr_list = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]
print(stack_arrays_vertically(arr_list))



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
#21 Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

def create_range_array(start, stop, step):
    return np.arange(start, stop + 1, step)

print(create_range_array(1, 10, 2))


[1 3 5 7 9]


In [26]:
#22 Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive). 
 
def generate_spaced_values():
    return np.linspace(0, 1, 10)

print(generate_spaced_values())


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [27]:

# 23 Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).


def generate_log_space():
    return np.logspace(0, 3, 5, base=10.0)

print(generate_log_space())


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [28]:
# 24 Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

import pandas as pd

data = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(data, columns=['A', 'B', 'C'])
print(df)


    A   B   C
0  65  73  61
1  61  62  88
2  60  42  66
3  17  46  21
4  72  29   2


In [29]:
# 25  Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

def replace_negatives_with_zeros(df, column):
    df[column] = np.where(df[column] < 0, 0, df[column])
    return df

df = pd.DataFrame({'A': [1, -2, 3], 'B': [-4, 5, -6]})
print(replace_negatives_with_zeros(df, 'A'))


   A  B
0  1 -4
1  0  5
2  3 -6


In [30]:
# 26  Access the 3rd element from the given NumPy array.

arr = np.array([10, 20, 30, 40, 50])
print(arr[2])




30


In [31]:
# 27 Retrieve the element at index (1, 2) from the 2D NumPy array.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1, 2])


6


In [32]:
# 28 Using boolean indexing, extract elements greater than 5 from the given NumPy array.

arr = np.array([3, 8, 2, 10, 5, 7])
print(arr[arr > 5])



[ 8 10  7]


In [33]:
# 29 Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[2:6])



[3 4 5 6]


In [34]:
# 30 Slice the 2D NumPy array to extract the sub-array [[2, 3], [5, 6]] from the given array.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[0:2, 1:3])


[[2 3]
 [5 6]]


In [35]:
# 31 Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

def extract_elements(arr, indices):
    return arr[tuple(indices.T)]

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([[0, 1], [1, 2], [2, 0]])
print(extract_elements(arr_2d, indices))


[2 6 7]


In [36]:
# 32 Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

def filter_greater_than(arr, threshold):
    return arr[arr > threshold]

arr = np.array([1, 2, 3, 4, 5])
print(filter_greater_than(arr, 3))

[4 5]


In [38]:
# 33 Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.


def extract_elements_3d(arr, idx0, idx1, idx2):
    return arr[idx0, idx1, idx2]

arr_3d = np.arange(27).reshape(3, 3, 3)
idx0 = np.array([0, 1, 2])
idx1 = np.array([1, 2, 0])
idx2 = np.array([2, 0, 1])
print(extract_elements_3d(arr_3d, idx0, idx1, idx2))

[ 5 15 19]


In [39]:
# 34 Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.


def filter_two_conditions(arr, cond1, cond2):
    return arr[np.logical_and(cond1, cond2)]

arr = np.array([1, 2, 3, 4, 5, 6])
cond1 = arr > 2
cond2 = arr < 5
print(filter_two_conditions(arr, cond1, cond2))

[3 4]


In [40]:
# 35 Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.


def extract_elements_2d(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
print(extract_elements_2d(arr_2d, row_indices, col_indices))

[2 6 7]


In [41]:
# 36 Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr + 5)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [42]:
# 37 Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
print(arr2 * arr1.T)

[[ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]


In [43]:
# 38 Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.


arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[5, 6, 7], [8, 9, 10], [11, 12, 13], [14, 15, 16]])
print(arr2 + arr1[:, None])

[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [44]:
# 39 Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])
print(arr1 + arr2)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [47]:
# 40 Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy.

import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10], [11, 12]])
result = np.dot(arr1, arr2)
print(result)

[[ 58  64]
 [139 154]]


In [48]:
# 41 Calculate column-wise mean for the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])
column_mean = np.mean(arr, axis=0)
print(column_mean)

[2.5 3.5 4.5]


In [49]:
# 42 Find maximum value in each row of the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])
row_max = np.max(arr, axis=1)
print(row_max)


[3 6]


In [50]:
# 43 For the given array, find indices of maximum value in each column:

arr = np.array([[1, 2, 3], [4, 5, 6]])
max_indices = np.argmax(arr, axis=0)
print(max_indices)


[1 1 1]


In [51]:
# 44 For the given array, apply custom function to calculate moving sum along rows:

def moving_sum(arr, window_size):
    return np.array([np.convolve(row, np.ones(window_size), 'valid') for row in arr])

arr = np.array([[1, 2, 3], [4, 5, 6]])
result = moving_sum(arr, 2)
print(result)


[[ 3.  5.]
 [ 9. 11.]]


In [52]:
# 45 In the given array, check if all elements in each column are even:


arr = np.array([[2, 4, 6], [3, 5, 7]])
all_even_columns = np.all(arr % 2 == 0, axis=0)
print(all_even_columns)

[False False False]


In [53]:
# 46 Given a NumPy array arr, reshape it into a matrix of dimensions m rows and n columns. Return the reshaped matrix:


def reshape_array(arr, m, n):
    return arr.reshape((m, n))

original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = reshape_array(original_array, 2, 3)
print(reshaped_array)


[[1 2 3]
 [4 5 6]]


In [54]:
# 47 Create a function that takes a matrix as input and returns the flattened array:

def flatten_matrix(matrix):
    return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print(flattened_array)


[1 2 3 4 5 6]


In [55]:
# 48 Write a function that concatenates two given arrays along a specified axis:

def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatenated_array = concatenate_arrays(array1, array2, axis=0)
print(concatenated_array)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [56]:
# 49 Create a function that splits an array into multiple sub-arrays along a specified axis:

def split_array(arr, indices_or_sections, axis=0):
    return np.split(arr, indices_or_sections, axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
splitted_arrays = split_array(original_array, 3, axis=0)
for sub_array in splitted_arrays:
    print(sub_array)

[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


In [57]:
# 50 Write a function that inserts and then deletes elements from a given array at specified indices:

def insert_and_delete(arr, indices_to_insert, values_to_insert, indices_to_delete):
    arr = np.insert(arr, indices_to_insert, values_to_insert)
    arr = np.delete(arr, indices_to_delete)
    return arr

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
modified_array = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(modified_array)

[ 1 10  4 11  5]


In [58]:
# 51 Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 10. Perform element-wise addition between arr1 and arr2:



arr1 = np.random.randint(1, 100, size=10)
arr2 = np.arange(1, 11)
sum_array = arr1 + arr2
print(sum_array)

[ 31  36   9  92  18  61  70  53 106  33]


In [59]:
# 52 Generate a NumPy array arr1 with sequential integers from 10 to 1 and another array arr2 with integers from 1 to 10. Subtract arr2 from arr1 element-wise:

arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
diff_array = arr1 - arr2
print(diff_array)


[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [60]:
# 53 Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 5. Perform element-wise multiplication between arr1 and arr2:

arr1 = np.random.randint(1, 100, size=5)
arr2 = np.arange(1, 6)
product_array = arr1 * arr2
print(product_array)

[ 56 140 213 324 295]


In [61]:
# 54 Generate a NumPy array arr1 with even integers from 2 to 10 and another array arr2 with integers from 1 to 5. Perform element-wise division of arr1 by arr2:

arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)
div_array = arr1 / arr2
print(div_array)


[2. 2. 2. 2. 2.]


In [62]:
# 55 Create a NumPy array arr1 with integers from 1 to 5 and another array arr2 with the same numbers reversed. Calculate the exponentiation of arr1 raised to the power of arr2 element-wise:

arr1 = np.arange(1, 6)
arr2 = arr1[::-1]
exp_array = arr1 ** arr2
print(exp_array)


[ 1 16 27 16  5]


In [63]:
# 56 Write a function that counts the occurrences of a specific substring within a NumPy array of strings:

def count_substring_occurrences(arr, substring):
    return np.char.count(arr, substring)

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring_count = count_substring_occurrences(arr, 'hello')
print(substring_count)

[1 0 1 0 1]


In [65]:
#  57 Extract uppercase characters from NumPy array of strings


def extract_uppercase_chars(arr):
    
    char_array = np.char.array(arr).view('U1')
   
    flattened = char_array.flatten()
   
    uppercase_chars = flattened[np.char.isupper(flattened)]
    return uppercase_chars

arr = np.array(['DataScience', 'MachineLearning', 'NumPy', 'Python'])
uppercase_chars = extract_uppercase_chars(arr)
print(uppercase_chars)


['D' 'S' 'M' 'L' 'N' 'P' 'P']


In [66]:
# 58 Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string:

def replace_substring(arr, old_substring, new_substring):
    return np.char.replace(arr, old_substring, new_substring)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
replaced_array = replace_substring(arr, 'apple', 'fruit')
print(replaced_array)


['fruit' 'banana' 'grape' 'pinefruit']


In [68]:
# 59 Write a function that concatenates strings in a NumPy array element-wise:

def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(['numpy', 'pandas'])
arr2 = np.array(['machine', 'learning'])
concatenated_array = concatenate_strings(arr1, arr2)
print(concatenated_array)


['numpymachine' 'pandaslearning']


In [69]:
# 60 Write a function that finds the length of the longest string in a NumPy array:

def find_longest_string_length(arr):
    return np.max(np.char.str_len(arr))

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
longest_length = find_longest_string_length(arr)
print(longest_length)

9


In [70]:
# 61 Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions:

data = np.random.randint(1, 1001, size=100)
mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)
print(f"Mean: {mean}, Median: {median}, Variance: {variance}, Standard Deviation: {std_dev}")

Mean: 518.6, Median: 518.5, Variance: 87180.34000000003, Standard Deviation: 295.2631707477247


In [71]:
# 62 Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset:


data = np.random.randint(1, 101, size=50)
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)
print(f"25th Percentile: {percentile_25}, 75th Percentile: {percentile_75}")

25th Percentile: 24.75, 75th Percentile: 77.5


In [72]:
# 63 Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's corrcoef function:

arr1 = np.random.randint(1, 100, size=10)
arr2 = np.random.randint(1, 100, size=10)
correlation = np.corrcoef(arr1, arr2)
print(correlation)


[[ 1.         -0.37661035]
 [-0.37661035  1.        ]]


In [73]:
# 64 Create two matrices and perform matrix multiplication using NumPy's dot function:

matrix1 = np.random.randint(1, 10, size=(3, 2))
matrix2 = np.random.randint(1, 10, size=(2, 3))
product_matrix = np.dot(matrix1, matrix2)
print(product_matrix)

[[ 50  97  13]
 [ 55 106  14]
 [ 24  46   6]]


In [74]:
# 65 Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles:


data = np.random.randint(10, 1001, size=50)
percentile_10 = np.percentile(data, 10)
median = np.median(data)
percentile_90 = np.percentile(data, 90)
first_quartile = np.percentile(data, 25)
third_quartile = np.percentile(data, 75)
print(f"10th Percentile: {percentile_10}, Median: {median}, 90th Percentile: {percentile_90}, Q1: {first_quartile}, Q3: {third_quartile}")

10th Percentile: 182.3, Median: 527.0, 90th Percentile: 876.3000000000001, Q1: 281.75, Q3: 763.0


In [75]:
# 66 Create a NumPy array of integers and find the index of a specific element:

arr = np.array([10, 20, 30, 40, 50])
index = np.where(arr == 30)
print(index)


(array([2]),)


In [76]:
# 67 Generate a random NumPy array and sort it in ascending order:

arr = np.random.randint(1, 100, size=10)
sorted_arr = np.sort(arr)
print(sorted_arr)


[ 1 18 28 44 61 61 72 77 80 98]


In [77]:
# 68 Filter elements > 20 in the given NumPy array:

arr = np.array([12, 25, 6, 42, 8, 30])
filtered_arr = arr[arr > 20]
print(filtered_arr)

[25 42 30]


In [78]:
# 69 Filter elements which are divisible by 3 from a given NumPy array:

arr = np.array([1, 5, 8, 12, 15])
divisible_by_3 = arr[arr % 3 == 0]
print(divisible_by_3)

[12 15]


In [79]:
# 70 Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array:

arr = np.array([10, 20, 30, 40, 50])
filtered_arr = arr[(arr >= 20) & (arr <= 40)]
print(filtered_arr)


[20 30 40]


In [80]:
#  71 Check byte order of array
import numpy as np

arr = np.array([1, 2, 3])
print(arr.dtype.byteorder)


=


In [81]:
#  72`` Perform byte swapping in place
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)
print(arr)


[16777216 33554432 50331648]


In [82]:
#  73 Swap byte order without modifying original array
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
swapped_arr = arr.newbyteorder()
print(swapped_arr)
print(arr)  # Original array remains unchanged


[16777216 33554432 50331648]
[1 2 3]


In [83]:
#  74 Swap byte order based on system endianness
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder == '=':  # System's native byte order
    swapped_arr = arr.newbyteorder()
else:
    swapped_arr = arr

print(swapped_arr)


[16777216 33554432 50331648]


In [84]:
#  75 Check if byte swapping is necessary
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
byte_order = arr.dtype.byteorder
is_swapping_needed = byte_order == '>'
print(is_swapping_needed)


False


In [85]:
#  76 Create copy of array and modify element
import numpy as np

arr1 = np.array([1, 2, 10])
copy_arr = arr1.copy()
copy_arr[0] = 100
print(copy_arr)
print(arr1)  # Original array remains unchanged


[100   2  10]
[ 1  2 10]


In [86]:
#  77 Extract slice from 2D array and modify element
import numpy as np

matrix = np.random.randint(0, 10, size=(3, 3))
view_slice = matrix[:, 1]
view_slice[0] = 999
print(matrix)  # Original array reflects changes


[[  6 999   7]
 [  8   7   9]
 [  4   5   3]]


In [87]:
#  78 Broadcast addition to slice and check if original array is altered
import numpy as np

array_a = np.arange(1, 13).reshape((4, 3))
view_b = array_a[:, :2]
view_b += 5
print(array_a)  # Original array reflects changes


[[ 6  7  3]
 [ 9 10  6]
 [12 13  9]
 [15 16 12]]


In [88]:
#  79 Create reshaped view and modify element
import numpy as np

orig_array = np.arange(1, 9).reshape((2, 4))
reshaped_view = orig_array.reshape((4, 2))
reshaped_view[0, 0] = 999
print(orig_array)  # Original array reflects changes


[[999   2   3   4]
 [  5   6   7   8]]


In [89]:
#  80 Extract copy of elements > 5 and modify it
import numpy as np

data = np.random.randint(0, 10, size=(3, 4))
data_copy = data[data > 5].copy()
if data_copy.size > 0:
    data_copy[0] = 999
print(data)  # Original array remains unchanged


[[4 6 9 3]
 [6 6 1 7]
 [0 2 1 3]]


In [90]:
#  81 Perform addition and subtraction between two matrices
import numpy as np

A = np.random.randint(0, 10, size=(3, 3))
B = np.random.randint(0, 10, size=(3, 3))
sum_matrix = A + B
diff_matrix = A - B
print("Sum:\n", sum_matrix)
print("Difference:\n", diff_matrix)


Sum:
 [[ 3 12 11]
 [ 8  8  9]
 [ 0  9  9]]
Difference:
 [[ 1  4  5]
 [-6  0  1]
 [ 0  1  9]]


In [91]:
#  82 Perform matrix multiplication
import numpy as np

C = np.random.randint(0, 10, size=(3, 2))
D = np.random.randint(0, 10, size=(2, 4))
result = np.dot(C, D)
print(result)


[[20 66 16 26]
 [20 36 11 46]
 [14 27  8 31]]


In [92]:
#  83 Find transpose of a matrix
import numpy as np

E = np.random.randint(0, 10, size=(3, 3))
transpose_E = E.T
print(transpose_E)


[[0 9 8]
 [3 0 0]
 [8 9 3]]


In [93]:
#  84 Compute determinant of a square matrix
import numpy as np

F = np.random.randint(0, 10, size=(3, 3))
det_F = np.linalg.det(F)
print(det_F)


122.99999999999994


In [94]:
#  84 Compute determinant of a square matrix
import numpy as np

F = np.random.randint(0, 10, size=(3, 3))
det_F = np.linalg.det(F)
print(det_F)


248.00000000000009


In [95]:
#  85 Find inverse of a square matrix
import numpy as np

G = np.random.randint(1, 10, size=(3, 3))
inverse_G = np.linalg.inv(G)
print(inverse_G)


[[ 0.23529412 -0.64705882  0.05882353]
 [-0.12941176  0.70588235 -0.08235294]
 [-0.08235294  0.17647059  0.12941176]]
